import type { DsaProblem } from "./types";

export const CATALOG_EASY: DsaProblem[] = [
  {
    slug: "two-sum",
    title: "Two Sum",
    difficulty: "easy",
    tags: ["Array", "Hash Map"],
    prompt: "Given an array of integers `nums` and an integer `target`, return the indices of the two numbers that add up to `target`. Each input has exactly one solution; you may not use the same element twice.",
    examples: [{ input: "nums = [2,7,11,15], target = 9", output: "[0,1]", explanation: "nums[0] + nums[1] = 9" }],
  },
  {
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    difficulty: "easy",
    tags: ["Stack", "String"],
    prompt: "Given a string `s` containing just '()[]{}', determine if the input string is valid — brackets must close in the correct order.",
    examples: [{ input: 's = "()[]{}"', output: "true" }, { input: 's = "(]"', output: "false" }],
  },
  {
    slug: "reverse-linked-list",
    title: "Reverse Linked List",
    difficulty: "easy",
    tags: ["Linked List", "Recursion"],
    prompt: "Given the head of a singly linked list, reverse the list and return the new head.",
    examples: [{ input: "head = [1,2,3,4,5]", output: "[5,4,3,2,1]" }],
  },
  {
    slug: "binary-search",
    title: "Binary Search",
    difficulty: "easy",
    tags: ["Binary Search", "Array"],
    prompt: "Given a sorted array `nums` and a `target`, return its index, or -1 if it doesn't exist. Must run in O(log n).",
    examples: [{ input: "nums = [-1,0,3,5,9,12], target = 9", output: "4" }],
  },
  {
    slug: "contains-duplicate",
    title: "Contains Duplicate",
    difficulty: "easy",
    tags: ["Array", "Hash Map"],
    prompt: "Given an integer array `nums`, return true if any value appears at least twice in the array, and false if every element is distinct.",
    examples: [
      { input: "nums = [1,2,3,1]", output: "true" },
      { input: "nums = [1,2,3,4]", output: "false" },
    ],
  },
  {
    slug: "climbing-stairs",
    title: "Climbing Stairs",
    difficulty: "easy",
    tags: ["Dynamic Programming", "Math"],
    prompt: "You're climbing a staircase of `n` steps. Each move you can climb 1 or 2 steps. Return the number of distinct ways to reach the top.",
    examples: [
      { input: "n = 2", output: "2", explanation: "1+1 or 2" },
      { input: "n = 3", output: "3", explanation: "1+1+1, 1+2, 2+1" },
    ],
  },
  // --- Confidence-building starter set: classic first-week exercises, deliberately simpler than
  // the problems above, so a brand-new coder has an easy on-ramp before Two Sum/Valid Parentheses.
  {
    slug: "fizzbuzz",
    title: "FizzBuzz",
    difficulty: "easy",
    tags: ["Math"],
    prompt: "Given an integer `n`, return a string array of length `n` where, for each number from 1 to n: if it's divisible by 3 output \"Fizz\", by 5 output \"Buzz\", by both output \"FizzBuzz\", otherwise the number itself as a string.",
    examples: [{ input: "n = 5", output: '["1","2","Fizz","4","Buzz"]' }],
  },
  {
    slug: "reverse-string",
    title: "Reverse a String",
    difficulty: "easy",
    tags: ["String", "Two Pointers"],
    prompt: "Given a string `s`, return the string reversed.",
    examples: [{ input: 's = "hello"', output: '"olleh"' }],
  },
  {
    slug: "palindrome-check",
    title: "Palindrome Check",
    difficulty: "easy",
    tags: ["String", "Two Pointers"],
    prompt: "Given a string `s`, return true if it reads the same forwards and backwards, ignoring case and any non-alphanumeric characters (spaces, punctuation).",
    examples: [
      { input: 's = "racecar"', output: "true" },
      { input: 's = "A man a plan a canal Panama"', output: "true", explanation: "ignoring case and spaces" },
    ],
  },
  {
    slug: "factorial",
    title: "Factorial of a Number",
    difficulty: "easy",
    tags: ["Math", "Recursion"],
    prompt: "Given a non-negative integer `n`, return `n!` (the product of all positive integers up to n). By definition, 0! = 1.",
    examples: [{ input: "n = 5", output: "120", explanation: "5*4*3*2*1" }],
  },
  {
    slug: "sum-of-array",
    title: "Sum of an Array",
    difficulty: "easy",
    tags: ["Array"],
    prompt: "Given an array of integers `nums`, return the sum of all its elements. An empty array sums to 0.",
    examples: [{ input: "nums = [1,2,3,4,5]", output: "15" }],
  },
  {
    slug: "find-maximum",
    title: "Find the Maximum Element",
    difficulty: "easy",
    tags: ["Array"],
    prompt: "Given a non-empty array of integers `nums`, return the largest element.",
    examples: [{ input: "nums = [3,1,4,1,5,9,2,6]", output: "9" }],
  },
  {
    slug: "count-vowels",
    title: "Count Vowels in a String",
    difficulty: "easy",
    tags: ["String"],
    prompt: "Given a string `s`, return the count of vowel characters (a, e, i, o, u — case-insensitive) in it.",
    examples: [{ input: 's = "Programming"', output: "3" }],
  },
  {
    slug: "is-prime",
    title: "Check Prime Number",
    difficulty: "easy",
    tags: ["Math"],
    prompt: "Given an integer `n`, return true if it's a prime number (greater than 1, with no positive divisors other than 1 and itself), false otherwise.",
    examples: [
      { input: "n = 7", output: "true" },
      { input: "n = 15", output: "false", explanation: "3 x 5" },
    ],
  },
  {
    slug: "fibonacci-nth",
    title: "Nth Fibonacci Number",
    difficulty: "easy",
    tags: ["Math", "Recursion", "Dynamic Programming"],
    prompt: "Given an integer `n` (0-indexed), return the nth Fibonacci number, where fib(0) = 0, fib(1) = 1, and fib(n) = fib(n-1) + fib(n-2).",
    examples: [
      { input: "n = 6", output: "8" },
      { input: "n = 10", output: "55" },
    ],
  },
];
