/**
 * DSA judging metadata — the centralized, version-controlled test cases (LeetCode-style: few but
 * powerful, edge cases included). Students implement a single `solve(...)` entry point; the
 * execution engine feeds each test's `args` as JSON and compares the returned value.
 *
 * Split by difficulty across easy.ts/medium.ts/hard.ts to keep individual files scannable as the
 * catalog grows. reverse-linked-list and lru-cache need a node type / a design-class op-sequence —
 * deferred and stay review-only (NOT auto-graded, never a fake pass).
 *
 * Expected values are hand-verified (or generated by scripts/dsa-verify against a reference
 * solution) — a wrong expected is a false-negative that punishes a correct solution, the exact
 * failure this feature must avoid.
 */
import type { Language } from "@studentos/execution";
import { JUDGING_EASY } from "./easy";
import { JUDGING_MEDIUM } from "./medium";
import { JUDGING_HARD } from "./hard";

export type { CompareMode, ProblemJudging } from "./types";

export const JUDGING: Record<string, import("./types").ProblemJudging> = {
  ...JUDGING_EASY,
  ...JUDGING_MEDIUM,
  ...JUDGING_HARD,
};

/** Problems with auto-grading wired (the rest stay review-only for now). */
export function isGraded(slug: string): boolean {
  return slug in JUDGING;
}

/** Sample (visible) tests only — used by Run. Never leak the hidden tests to a client component. */
export function sampleTests(slug: string): { args: unknown[]; expected: unknown }[] {
  const j = JUDGING[slug];
  if (!j) return [];
  return j.tests.filter((t) => t.sample).map((t) => ({ args: t.args, expected: t.expected }));
}

/** Per-language starter stub the editor pre-fills. java/cpp land in a later step. */
export function starterFor(slug: string, language: Language): string | undefined {
  const j = JUDGING[slug];
  if (!j) return undefined;
  const args = j.params.join(", ");
  switch (language) {
    case "python":
      return `def solve(${args}):\n    # Write your solution here\n    `;
    case "javascript":
      return `function solve(${args}) {\n  // Write your solution here\n}`;
    case "typescript":
      return `${j.tsSig} {\n  // Write your solution here\n}`;
    default:
      return undefined;
  }
}
