/**
 * Live smoke test for the AI generation layer (#1).
 * Calls the AI Gateway for real and checks the output satisfies the contract.
 *
 *   AI_GATEWAY_API_KEY=... tsx scripts/smoke.ts
 */
import { generateReportContent } from "../src/report.js";

const res = await generateReportContent({
  title: "Waste Heat Recovery in IC Engines",
  reportType: "seminar",
  guidelines: "Focus on thermoelectric generators and organic Rankine cycle approaches.",
  targetWords: 1200,
  student: {
    name: "Aarav Sharma",
    roll: "ME21-047",
    department: "Mechanical Engineering",
    semester: "6",
    college: "Sardar Patel Institute of Technology",
    guide: "Prof. R. Deshmukh",
  },
});

console.log(`✓ generated by: ${res.model}`);
console.log(`  abstract   : ${res.content.abstract.slice(0, 110)}…`);
console.log(`  sections   : ${res.content.sections.length} →`, res.content.sections.map((s) => s.heading));
console.log(`  references : ${res.content.references.length}`);
console.log("✓ PASS — model output validated against the ReportContent contract.");
